---
title: "Project 2: Unveiling Ecological Dynamics Through Simulation and Visualization of Biodiversity Data Cubes"
subtitle: "Framework architecture"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
bibliography: references.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
# Setup
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here())

# Packages
library(tidyverse)
library(sf)
```

# Introduction

# Project architecture

## Occurrence process

### Description

```         
simulate_occurrences(
    polygon,
    density = rpois(1, rgamma(1, 50, 1)),
    spatial_clustering = c("random", "clustered", "regular"),
    time_points = 1,
    temporal_autocorr = ifelse(time_points ==  1, NA, "random_walk"),
    spatial_autocorr = NA,
    seed = NA) {
 ...
}
```

### Function arguments

### Returns

## Detection process

### Description

The function `simulate_observations()` samples observations from occurrences based on detection probability and sampling bias.

```         
simulate_observations(
    occurrences,
    detection_probability = 1,
    sampling_bias = c("no_bias", "polygon", "manual"),
    bias_area = NA,
    bias_strength = NA,
    bias_weights = NA,
    coordinate_uncertainty_meters = 25,
    seed = NA) {
 ...
}
```

The function `add_coordinate_uncertainty()` is a helper function for `simulate_observations()` to add a `coordinateUncertaintyInMeters` column that should also be openly available in case users simulate observations based on virtual species distributions. This can for example be accomplished using the **virtualspecies** package [@leroy2016virtualspecies]:

1.  Species-environment relationship
    -   `generateSpFromFun()`
    -   `generateSpFromPCA()`
2.  Conversion to presence-absence
    -   `convertToPA()`
    -   introduce distribution bias: `limitDispersal()`
3.  Sample occurrences
    -   `sampleOccurrences()`
4.  Convert to sf object with POINT geometry
    -   `sf::st_as_sf()`

```         
add_coordinate_uncertainty(
    occurrences,
    coordinate_uncertainty_meters = 25) {
 ...
}
```

### Function arguments

**occurrences**:

An sf object with POINT geometry.

**detection_probability**:

A numeric value between 0 and 1, corresponding to the probability of detection of the species.

**sampling_bias**:

`"no_bias"`, `"polygon"` or `"manual"`. The method used to generate a sampling bias.

-   `"polygon"`: bias the sampling in a polygon. Provide your polygon to `bias_area`. Provide bias strength to `bias_strength`.
-   `"manual"`: bias the sampling manually via a raster. Provide your raster layer in which each cell contains the probability to be sampled to `bias_weights`.

**bias_area**:

`NA` or an sf object with POLYGON geometry. Only used if `sampling_bias = "polygon"`. The area in which the sampling will be biased.

**bias_strength**:

`NA` or a positive numeric value. Only used if `sampling_bias = "polygon"`. The strength of the bias to be applied in the biased area (as a multiplier). Above 1, area will be oversampled. Below 1, area will be undersampled. For example, a value of 50 will result in 50 times more samples within the `bias_area` than outside. Conversely, a value of 0.5 will result in half less samples within the `bias_area` than outside.

**bias_weights**:

`NA` or a raster layer (sf object with POLYGON geometry, or SpatRaster object). Only used if `sampling_bias = "manual"`. The raster of bias weights to be applied to the sampling of occurrences. Higher weights mean a higher probability of sampling. Weights can be numeric values between 0 and 1 or positive integers that will be rescaled to values between 0 and 1.

**coordinate_uncertainty_meters**:

A positive numeric value or vector with length `nrow(occurrences)` describing the uncertainty in meters around each observation.

**seed**:

A positive numeric value. The seed for random number generation to make results reproducible. If `NA` (the default), no seed is used.

### Returns

An sf object with POINT geometry containing the sampled observations, a `detection_probability` column, a `bias_weight` and a `coordinateUncertaintyInMeters` column.

## Grid designation process

### Description

The function `grid_designation()` designates observations to cells of a given grid to create an aggregated data cube.

```         
grid_designation(
    observations,
    grid,
    id_col = "row_names",
    seed = NA,
    aggregate = TRUE,
    randomisation = c("uniform", "normal"),
    p_norm = ifelse(tolower(randomisation[1]) ==  "uniform", NA, 0.95)) {
 ...
}
```

### Function arguments

**observations**:

An sf object with POINT geometry and a `coordinateUncertaintyInMeters` column. If this column is not present, the function will assume no (zero meters) uncertainty around the observation points.

**grid**:

An sf object with POLYGON geometry (usually a grid) to which observations should be designated.

**id_col**:

The column name of the column with unique ids for each grid cell. If `"row_names"` (the default), a new column `id` is created were the row names represent the unique ids.

**seed**:

A positive numeric value. The seed for random number generation to make results reproducible. If `NA` (the default), no seed is used.

**aggregate**:

Logical. If `TRUE` (default), return data cube in aggregated form (grid with number of observations per grid cell). Otherwise return sampled points in uncertainty circle.

**randomisation**:

`"uniform"` or `"normal"`. Randomisation method used for sampling within uncertainty circle around each observation. By default `"uniform"` which means each point uncertainty circle has an equal probability to be selected. The other option is `"normal"` where a point is sampled from a bivariate Normal distribution with means equal to the observation point and the variance equal to (-`coordinateUncertaintyInMeters`\^2) / (2 \* log(1 - `p_norm`)) such that `p_norm` % of all possible samples from this Normal distribution fall within the uncertainty circle.

**p_norm**:

A numeric value between 0 and 1. Only used if `randomisation = "normal"`. The proportion of all possible samples from a a bivariate Normal distribution that fall within the uncertainty circle. If normal randomisation is used and no value is given, the default `p_norm` value is 0.95.

### Returns

In case of `aggregate = TRUE`, an sf object with the number of observations, POLYGON geometry and minimal coordinate uncertainty per grid cell. In case of `aggregate = FALSE`, an sf object with POINT geometry of the sampled observations in the uncertainty circle and the coordinate uncertainty in meters related to the original observation.

# References