---
title: "Project 2: Unveiling Ecological Dynamics Through Simulation and Visualization of Biodiversity Data Cubes"
subtitle: "Setup and introduction"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

```{r setup, include=FALSE}
# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here())
```

# Introduction

Ecological systems are inherently variable, and a single dataset does not capture the full range of possible conditions. Simulations allow us to explore a broader spectrum of scenarios, considering different combinations of variables and their interactions. Ecological processes unfold dynamically over time, and a single snapshot of data does not capture the temporal aspects. Simulations enable the modelling of dynamic processes, allowing researchers to observe and analyse changes over various time scales.
 
As far as we know, there is no simulation framework present for biodiversity data cubes. A simulation framework in this context would help to examine the generalisability of the (statistical) properties of biodiversity data cubes and the derived indicators. 


# Technical setup and requirements

Download R, RStudio, git

Set up RStudio, git

Clone GitHub repository [hackathon-projects-2024](https://github.com/b-cubed-eu/hackathon-projects-2024) in RStudio.

pull changes

create branches

push changes


# Monte Carlo simulation framework for biodiversity data cubes

In this project, we will aim to create a simulation framework for biodiversity data cubes based on [Monte Carlo methods](https://en.wikipedia.org/wiki/Monte_Carlo_method). 

We need to simulate three different processes. 

1.  occurrence process
2.  detection process
3.  grid designation process

This is related to different variables that depend on *species*, *observation*, *space* and *time*.


